const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const file=path.join(__dirname,'../motion/loader.js'),api=fs.existsSync(file)?require(file):{};
function fixture(){assert.equal(typeof api.create,'function');const events=[],timers=new Map(),frames=[];let n=0;const loader=api.create({show:()=>events.push('show'),hide:()=>events.push('hide'),slow:()=>events.push('slow'),fail:()=>events.push('fail'),enter:(p,id)=>events.push(['enter',p,id]),setTimer:fn=>{timers.set(++n,fn);return n},clearTimer:id=>timers.delete(id),request:fn=>frames.push(fn)});return{loader,events,timers,frames,flush:()=>{while(frames.length)frames.shift()()}}}
test('ready frame releases the loader immediately without waiting for thumbnails',()=>{const f=fixture();f.loader.begin('kaido',1);f.loader.ready('kaido',1);assert.deepEqual(f.events,['show','hide']);assert.equal(f.timers.size,0);f.flush();assert.deepEqual(f.events.at(-1),['enter','kaido',1]);});
test('readiness from an earlier navigation cannot dismiss the current loader',()=>{const f=fixture();f.loader.begin('kaido',1);f.loader.begin('kaido',2);assert.equal(f.loader.ready('kaido',1),false);assert.equal(f.events.includes('hide'),false);f.loader.ready('kaido',2);assert.equal(f.events.at(-1),'hide');});
test('readiness for the other artist cannot dismiss a current navigation',()=>{const f=fixture();f.loader.begin('nova',3);assert.equal(f.loader.ready('kaido',3),false);assert.equal(f.events.includes('hide'),false);});
test('duplicate readiness causes only one entrance',()=>{const f=fixture();f.loader.begin('kaido',1);f.loader.ready('kaido',1);f.loader.ready('kaido',1);f.flush();assert.equal(f.events.filter(x=>Array.isArray(x)).length,1);assert.equal(f.events.filter(x=>x==='hide').length,1);});
test('an entrance queued before a newer navigation is ignored',()=>{const f=fixture();f.loader.begin('kaido',1);f.loader.ready('kaido',1);f.loader.begin('nova',2);f.flush();assert.equal(f.events.some(x=>Array.isArray(x)),false);});
test('an earlier slow timer does not change the new loader state',()=>{const f=fixture();f.loader.begin('kaido',1);const old=[...f.timers.values()][0];f.loader.begin('nova',2);old();assert.equal(f.events.includes('slow'),false);[...f.timers.values()][0]();assert.equal(f.events.at(-1),'slow');});
test('a failed navigation shows retry state and a new attempt can enter',()=>{const f=fixture();f.loader.begin('kaido',1);f.loader.fail('kaido',1,Error('decode'));assert.equal(f.events.at(-1),'fail');assert.equal(f.loader.ready('kaido',1),false);f.loader.begin('kaido',2);f.loader.ready('kaido',2);f.flush();assert.deepEqual(f.events.at(-1),['enter','kaido',2]);});
