const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const KNMotion=require('../motion/engine'),KNForms=require('../motion/forms');
module.exports=function fixture({enabled=true,width=1280,artist='nova'}={}){
 const frames=new Map(),windowHandlers=new Map(),documentHandlers=new Map(),intersections=[],sizes=[],mutations=[];let serial=0,layouts=0,paints=0,gold=false;
 const strokeColors=[],finite=(...args)=>args.filter(value=>typeof value==='number').forEach(value=>assert.ok(Number.isFinite(value),'renderer emitted a non-finite coordinate'));
 const ctx={clearRect(...a){finite(...a);paints++;},fillRect:finite,setTransform:finite,save(){},restore(){},translate:finite,beginPath(){},closePath(){},moveTo:finite,lineTo:finite,arc:finite,ellipse:finite,stroke(){},fill(){},createRadialGradient(...a){finite(...a);return {addColorStop:finite};},set strokeStyle(value){strokeColors.push(value);}};
 const canvas={getContext:()=>ctx},readout={textContent:'01 / KNOT'},logo={classList:{contains:()=>gold},addEventListener(){}};
 const controls=['knot','orbit','wave'].map(name=>({dataset:{sceneMode:name},attributes:{},addEventListener(type,fn){this[type]=fn;},setAttribute(name,value){this.attributes[name]=value;}}));
 const stage={dataset:{sceneArtist:artist},parentElement:{querySelectorAll:()=>controls},querySelector:selector=>selector==='canvas'?canvas:selector==='.kn-form-readout'?readout:selector==='#novaLogoStage'&&artist==='nova'?logo:null,getBoundingClientRect(){layouts++;return {width:480,height:462,left:0,top:0};},addEventListener(){}};
 const listen=(map,type,fn)=>{if(!map.has(type))map.set(type,[]);map.get(type).push(fn);},emit=(map,type)=>map.get(type)?.forEach(fn=>fn());
 const document={hidden:false,querySelectorAll:()=>[stage],addEventListener:(type,fn)=>listen(documentHandlers,type,fn)};
 const context={KNMotion,KNForms,document,innerWidth:width,devicePixelRatio:2,navigator:{hardwareConcurrency:8},matchMedia:()=>({matches:false}),requestAnimationFrame(fn){frames.set(++serial,fn);return serial;},cancelAnimationFrame:id=>frames.delete(id),addEventListener:(type,fn)=>listen(windowHandlers,type,fn),knCanAnimate:()=>enabled,
  IntersectionObserver:class{constructor(fn){this.fn=fn;intersections.push(this);}observe(){}disconnect(){this.disconnected=true;}},ResizeObserver:class{constructor(fn){this.fn=fn;sizes.push(this);}observe(){}disconnect(){this.disconnected=true;}},MutationObserver:class{constructor(fn){this.fn=fn;mutations.push(this);}observe(){}disconnect(){this.disconnected=true;}}};
 context.window=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../motion/scene.js'),'utf8'),context);
 return {canvas,controls,readout,strokeColors,enter:()=>context.knEnterScenes(),get pending(){return frames.size;},get layouts(){return layouts;},get paints(){return paints;},step(time){const work=[...frames.values()];frames.clear();work.forEach(fn=>fn(time));},offscreen(value){intersections[0].fn([{isIntersecting:!value}]);},hidden(value){document.hidden=value;emit(documentHandlers,'visibilitychange');},motion(value){enabled=value;emit(windowHandlers,'KN_MOTION_CHANGE');},setGold(value){gold=value;mutations.forEach(observer=>observer.fn([{attributeName:'class'}]));},leave(){emit(windowHandlers,'pagehide');},get observersClosed(){return [...intersections,...sizes,...mutations].every(observer=>observer.disconnected);}};
};
